nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmScopes:
  trilon:
    npmRegistryServer: 'https://registry.npmjs.org/'
    npmPublishRegistry: 'https://registry.npmjs.org/'
    npmAlwaysAuth: true
    npmAuthToken: ${env:NPM_TOKEN}